### ISSUE TITLE
Allow middleware execution prior schema validation

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/core#4]
**Is your feature request related to a problem? Please describe.**
In case binary serialization packages are used, built in schema validation is not useable.

**Describe the solution you'd like**
We would like to have to be able to create a middleware where we deserialize request content before schema validation. For example using https://msgpack.org/ as the deserialization package.

**Describe alternatives you've considered**
Currently, SugoiJS schema validation is not usable if the content of the request is serialized using https://msgpack.org/

**Comment by o-b-one** [comment]
Hi @hilfor,
I rely on the fact you wanted to open it under @sugoi/server

Consider using @sugoi/server hooks which run before any request and after any request.
More information can be found here:
https://wiki.sugoijs.com/sugoi-server/hooks

**Comment by hilfor** [comment]
Hi @o-b-one ,
My mistake, this should have been opened under @sugoi/server . 

Before and After hooks is exactly what we need! 
Awesome stuff! Thanks a lot!
